trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: 'custom'
    customCommand: 'run test:ci'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: true
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: Npm@1
  displayName: 'npm pack'
  inputs:
    command: 'custom'
    customCommand: 'pack'
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    Contents: '*.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'