name: '1.1.$(Rev:r)'

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: version
  value: $(Build.BuildNumber)

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: 'custom'
    customCommand: 'run test:ci'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    failTaskOnFailedTests: true
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: FileTransform@1
  displayName: 'Update version number'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/'
    fileType: 'json'
    targetFiles: 'package.json'
- task: Npm@1
  displayName: 'npm pack'
  inputs:
    command: 'custom'
    customCommand: 'pack'
- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    Contents: '*.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'